// Zombie and Super-Zombie auto-features from the rules
export const ZOMBIE_FEATURES = [
  {
    id: "zombie-stamina-wounds",
    name: "No Stamina",
    description: "Zombies do not possess any Stamina. Instead, they only possess Wounds.",
    type: "trait" as const,
    autoGenerated: true,
    source: "Zombie Template"
  },
  {
    id: "strength-of-damned",
    name: "Strength of the Damned",
    description: "These zombies are much stronger than their former selves, raising their strength score to 18.",
    type: "trait" as const,
    autoGenerated: true,
    source: "Zombie Template"
  },
  {
    id: "bestial-instincts",
    name: "Bestial Instincts",
    description: "Zombies have all their intelligence, wisdom, and charisma reduced to 4. Zombies with this feature are unable to speak or understand language. They lose any skill set they may have had in life and now possess Zombie Senses and Strength of the Damned skill sets.",
    type: "trait" as const,
    autoGenerated: true,
    source: "Zombie Template"
  },
  {
    id: "zombie-immunities",
    name: "Zombie Immunities",
    description: "Immune to: Exhaustion, Frightened, Shaken, and Frightened. Immune to stun unless applied by an effect that utilizes electricity. Also immune to all mind-controlling powers, psychic damage, unless a power explicitly states that it affects zombies.",
    type: "immunity" as const,
    autoGenerated: true,
    source: "Zombie Template"
  },
  {
    id: "zombie-bite",
    name: "Zombie Bite",
    description: "A zombie's bite ignores 3 points of physical DR",
    type: "special" as const,
    autoGenerated: true,
    source: "Zombie Template"
  },
  {
    id: "attrition",
    name: "Attrition",
    description: "Zombies must feed to stay active. If they have not fed in a few months, they will slip into a semi-active state, remaining still like corpses for weeks on end. During this time, zombies decompose at a much slower rate and will 'wake up' when they hear any loud noise within 10 areas or smell a living creature within 3 Areas.",
    type: "trait" as const,
    autoGenerated: true,
    source: "Zombie Template"
  },
  {
    id: "enhanced-zombie-senses",
    name: "Enhanced Zombie Senses",
    description: "Zombies have enhanced senses for detecting living creatures.",
    type: "trait" as const,
    autoGenerated: true,
    source: "Zombie Template"
  },
  {
    id: "dead-head",
    name: "Dead Head",
    description: "Zombie trait indicating undead nature.",
    type: "trait" as const,
    autoGenerated: true,
    source: "Zombie Template"
  },
  {
    id: "speed-of-damned",
    name: "Speed of the Damned",
    description: "Zombie movement trait.",
    type: "trait" as const,
    autoGenerated: true,
    source: "Zombie Template"
  },
  {
    id: "relentless-nature",
    name: "Relentless Nature",
    description: "Zombies are relentless in their pursuit.",
    type: "trait" as const,
    autoGenerated: true,
    source: "Zombie Template"
  }
];

export const SUPER_Z_FEATURES = [
  {
    id: "super-z-stamina-wounds",
    name: "No Stamina",
    description: "Super Z's do not possess any Stamina. Instead, they only possess Wounds.",
    type: "trait" as const,
    autoGenerated: true,
    source: "Super Z Template"
  },
  {
    id: "unnatural-endurance",
    name: "Unnatural Endurance",
    description: "Super Z's gain +1 Wound",
    type: "trait" as const,
    autoGenerated: true,
    source: "Super Z Template"
  },
  {
    id: "super-z-strength",
    name: "Strength of the Damned",
    description: "All Super Z's are unnaturally strong, raising their strength score to a minimum of 20",
    type: "trait" as const,
    autoGenerated: true,
    source: "Super Z Template"
  },
  {
    id: "super-z-immunities",
    name: "Super Z Immunities",
    description: "Immune to: Exhaustion, Frightened, Shaken, and Frightened. Immune to stun unless applied by an effect that utilizes electricity. Also immune to all mind-controlling powers, psychic damage, unless a power explicitly states that it affects zombies.",
    type: "immunity" as const,
    autoGenerated: true,
    source: "Super Z Template"
  },
  {
    id: "super-z-bite",
    name: "Super Z Bite",
    description: "Super Z's bite ignores 4 points of physical DR",
    type: "special" as const,
    autoGenerated: true,
    source: "Super Z Template"
  },
  {
    id: "super-z-attrition",
    name: "Attrition",
    description: "Super Z's possess Attrition trait.",
    type: "trait" as const,
    autoGenerated: true,
    source: "Super Z Template"
  },
  {
    id: "super-z-enhanced-senses",
    name: "Enhanced Zombie Senses",
    description: "Super Z's possess enhanced zombie senses.",
    type: "trait" as const,
    autoGenerated: true,
    source: "Super Z Template"
  },
  {
    id: "super-z-dead-head",
    name: "Dead Head",
    description: "Super Z trait indicating undead nature.",
    type: "trait" as const,
    autoGenerated: true,
    source: "Super Z Template"
  },
  {
    id: "super-z-speed-damned",
    name: "Speed of the Damned",
    description: "Super Z movement trait.",
    type: "trait" as const,
    autoGenerated: true,
    source: "Super Z Template"
  }
];

export const DAMAGE_TYPES = [
  "Kinetic",
  "Slashing", 
  "Piercing",
  "Ballistic",
  "Energy",
  "Fire",
  "Cold",
  "Electrical",
  "Acid",
  "Psychic",
  "Necrotic"
];